USE GTT01NghiepVu 
GO
--Dinh nghia ma hq chuyen doi 
DECLARE @CucHQ varchar(2)='01' --chuyen cho Ha noi
--[GTT_TT] La LinkServer ket noi toi db GTT01NghiepVu do dia phuong gui len sau khi backup
Print '======================================================================='
Print 'Xoa du lieu tai DB GTT01NghiepVu tap trung'

Print '======================================================================='
Print 'Xoa thong tin danh muc rui ro'

Delete from GN_BangRRDeXuatChiCucCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRDeXuatChiCuc where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangRRDeXuatCucCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRDeXuatCuc where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangRRDeXuatTongCucCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRDeXuatTongCuc where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangRRCoSoCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRCoSo where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangDMRRSuDungCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangDMRRSuDung where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangRRSuDungXoaCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRSuDungCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangRRSuDung where substring(MA_HQQL,2,2)= @CucHQ


Delete from GN_BangTDDeXuatCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangTDDeXuat where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangTDCoSoCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangTDCoSo where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_BangDMTDSuDungCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangDMTDSuDung where substring(MA_HQQL,2,2)= @CucHQ


Delete from GN_BangTDSuDungXoaCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangTDSuDungCT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_BangTDSuDung where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Xoa thong tin cac to khai tri gia va ap gia'

Delete from GN_TKTGKB_PP1CT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGKB_PP1 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGKB_PP23 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGKB_PP4 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGKB_PP5 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGKB_PP6 where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_TKTGAG_PP1CT where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGAG_PP1 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGAG_PP23 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGAG_PP4 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGAG_PP5 where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TKTGAG_PP6 where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_ApGia where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_ApGia_XK where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Xoa thong tin khieu nai'

Delete from GN_KHIEUNAI_PICTURE where substring(MA_HQQL,2,2)= @CucHQ
Delete GN_KhieuNai_Hang 
from GN_KhieuNai_Hang A inner join GN_KhieuNai B
on A.ID_KHIEU_NAI=B.ID_KHIEU_NAI and A.MA_HQQL_KN=B.MA_HQQL
where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_KhieuNai where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Xoa thong tin cac nghiep vu Hai quan'

Delete from GN_KiemTraGia where substring(MA_HQQL,2,2)= @CucHQ
Delete GN_KiemTraSTQ_Hang 
from GN_KiemTraSTQ_Hang A inner join GN_KiemTraSTQ B
on A.MA_HQQL_STQ = B.MA_HQQL and A.ID_KIEM_TRA_STQ=B.ID_KIEM_TRA_STQ
where substring(MA_HQQL,2,2)= @CucHQ

Delete from GN_KiemTraSTQ where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_PhucTapGia where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_ThamVanGia where substring(MA_HQQL,2,2)= @CucHQ
Delete GN_ThanhTraGia_Hang 
from GN_ThanhTraGia_Hang A inner join GN_ThanhTraGia B 
on A.ID_THANH_TRA=B.ID_THANH_TRA and A.MA_HQQL_TT=B.MA_HQQL
where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_ThanhTraGia where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Xoa thong tin nguon khac'

Delete from GN_TTNguonKhac_Picture where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_TTNguonKhac where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Thong tin to khai va hang'
Delete from GN_HANG_PICTURE where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_GTT01Hang where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_GTT01HangKB where substring(MA_HQQL,2,2)= @CucHQ
Delete from GN_GTT01ToKhai where substring(MA_HQQL,2,2)= @CucHQ

Print '======================================================================='
Print 'Dong bo du lieu GTT01NghiepVu cuar cuc vao DB GTT01NghiepVu tap trung'

--GTT01. Kiem tra dong bo danh muc chuan
Print '======================================================================='
Print 'Kiem tra dong bo danh muc chuan'

--GTT01. Dong bo so lieu
Print '======================================================================='
Print 'Dong bo so lieu'

Set identity_insert [dbo].[GN_GTT01ToKhai] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_GTT01ToKhai]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[MA_HQ]
           ,[MA_LH]
           ,[NAM_DK]
           ,[SO_TK]
           ,[DANH_GIA_HSO]
           ,[DANH_GIA_TTHU]
           ,[STATUS]
           ,[NGAY_NM]
           ,[NGUOI_NM]
           ,[NGAY_DK])
SELECT     	
	[MA_HQQL]
	,[ID_TO_KHAI]
	,[MA_HQ]
	,[MA_LH]
	,[NAM_DK]
	,[SO_TK]
	,[DANH_GIA_HSO]
	,[DANH_GIA_TTHU]
	,[STATUS]
	,[NGAY_NM]
	,[NGUOI_NM]
	,[NGAY_DK]
FROM
	[GTT_TT].[GTT01NghiepVu].[dbo].[GN_GTT01ToKhai]
Set identity_insert [dbo].[GN_GTT01ToKhai] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_GTT01HangKB]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQ]
           ,[MA_LH]
           ,[NAM_DK]
           ,[SO_TK]
           ,[TKTG_KB]
           ,[DGIA_KB_TKTG]
           ,[MA_PLOAI_HANG]
           ,[MA_PLOAI_DGIA_KB])
	SELECT 
		[MA_HQQL]
		,[ID_TO_KHAI]
		,[ID_HANG]
		,[MA_HQ]
		,[MA_LH]
		,[NAM_DK]
		,[SO_TK]
		,[TKTG_KB]
		,[DGIA_KB_TKTG]
		,[MA_PLOAI_HANG]
		,[MA_PLOAI_DGIA_KB]	
	FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_GTT01HangKB]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_GTT01Hang]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQ]
           ,[MA_LH]
           ,[NAM_DK]
           ,[SO_TK]
           ,[TEN_TM]
           ,[NHA_SX]
           ,[KY_HIEU]
           ,[NGUYEN_LIEU]
           ,[KICH_CO]
           ,[NHAN_MAC]
           ,[CONG_DUNG]
           ,[CONG_SUAT]
           ,[CHAT_LUONG]
           ,[PP_CHE_TAO]
           ,[CO_THIET_KE]
           ,[MO_TA_KHAC]
           ,[MA_PLOAI_HANG]
           ,[SO_LUONG_THN_THX])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQ]
           ,[MA_LH]
           ,[NAM_DK]
           ,[SO_TK]
           ,[TEN_TM]
           ,[NHA_SX]
           ,[KY_HIEU]
           ,[NGUYEN_LIEU]
           ,[KICH_CO]
           ,[NHAN_MAC]
           ,[CONG_DUNG]
           ,[CONG_SUAT]
           ,[CHAT_LUONG]
           ,[PP_CHE_TAO]
           ,[CO_THIET_KE]
           ,[MO_TA_KHAC]
           ,[MA_PLOAI_HANG]
           ,[SO_LUONG_THN_THX]
	FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_GTT01Hang]         

Set identity_insert [dbo].[GN_HANG_PICTURE] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_HANG_PICTURE]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile]
     FROM
		 [GTT_TT].[GTT01NghiepVu].[dbo].[GN_HANG_PICTURE] 
Set identity_insert [dbo].[GN_HANG_PICTURE] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP1]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_TKTG]
           ,[NGAY_XK]
           ,[QUYEN_SD]
           ,[KHONG_XD]
           ,[TRA_THEM]
           ,[TIEN_PHAI_TRA]
           ,[CO_QHDB]
           ,[KIEU_QHDB]
           ,[ANH_HUONG_QH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
           ,[GHI_CHEP_HQ])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_TKTG]
           ,[NGAY_XK]
           ,[QUYEN_SD]
           ,[KHONG_XD]
           ,[TRA_THEM]
           ,[TIEN_PHAI_TRA]
           ,[CO_QHDB]
           ,[KIEU_QHDB]
           ,[ANH_HUONG_QH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
           ,[GHI_CHEP_HQ]
     FROM
     	[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP1] 

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP1CT]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_TKTG]
           ,[ID_HANG]
           ,[GIA_HOA_DON]
           ,[TT_GIAN_TIEP]
           ,[TRA_TRUOC]
           ,[TONG_CONG_1]
           ,[HOA_HONG]
           ,[PHI_BAO_BI]
           ,[PHI_DONG_GOI]
           ,[TRO_GIUP]
           ,[NGUYEN_LIEU]
           ,[VAT_LIEU]
           ,[CONG_CU]
           ,[THIET_KE]
           ,[BAN_QUYEN]
           ,[TIEN_TRA_SD]
           ,[PHI_VC]
           ,[CP_BH]
           ,[PHI_BH]
           ,[PHI_NOI_DIA]
           ,[TONG_CONG_2]
           ,[PHI_PHAT_SINH]
           ,[TIEN_LAI]
           ,[PHI_KHAC]
           ,[GIAM_GIA]
           ,[TONG_CONG_3]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_TKTG]
           ,[ID_HANG]
           ,[GIA_HOA_DON]
           ,[TT_GIAN_TIEP]
           ,[TRA_TRUOC]
           ,[TONG_CONG_1]
           ,[HOA_HONG]
           ,[PHI_BAO_BI]
           ,[PHI_DONG_GOI]
           ,[TRO_GIUP]
           ,[NGUYEN_LIEU]
           ,[VAT_LIEU]
           ,[CONG_CU]
           ,[THIET_KE]
           ,[BAN_QUYEN]
           ,[TIEN_TRA_SD]
           ,[PHI_VC]
           ,[CP_BH]
           ,[PHI_BH]
           ,[PHI_NOI_DIA]
           ,[TONG_CONG_2]
           ,[PHI_PHAT_SINH]
           ,[TIEN_LAI]
           ,[PHI_KHAC]
           ,[GIAM_GIA]
           ,[TONG_CONG_3]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP1CT]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP23]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[NGAY_XK]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_TT]
           ,[MA_HQ_TT]
           ,[MA_LH_TT]
           ,[NGAY_DK_TT]
           ,[SO_TK_TT]
           ,[STT_HANG_TT]
           ,[NGAY_XK_TT]
           ,[TRI_GIA_NT_TT]
           ,[DC_CD_TM]
           ,[DC_SL]
           ,[DC_GIAM_GIA]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[TKTG_PP2]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[NGAY_XK]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_TT]
           ,[MA_HQ_TT]
           ,[MA_LH_TT]
           ,[NGAY_DK_TT]
           ,[SO_TK_TT]
           ,[STT_HANG_TT]
           ,[NGAY_XK_TT]
           ,[TRI_GIA_NT_TT]
           ,[DC_CD_TM]
           ,[DC_SL]
           ,[DC_GIAM_GIA]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[TKTG_PP2]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP23]
		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP4]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_KT]
           ,[GIA_BAN_VN]
           ,[TL_GIA_BAN_VN]
           ,[DC_HOA_HONG]
           ,[TL_HOA_HONG]
           ,[DC_LOI_NHUAN]
           ,[TL_LOI_NHUAN]
           ,[DC_PHI_VT]
           ,[TL_PHI_VT]
           ,[DC_PHI_BH]
           ,[TL_PHI_BH]
           ,[DC_PHI_KHAC]
           ,[TL_PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_KT]
           ,[GIA_BAN_VN]
           ,[TL_GIA_BAN_VN]
           ,[DC_HOA_HONG]
           ,[TL_HOA_HONG]
           ,[DC_LOI_NHUAN]
           ,[TL_LOI_NHUAN]
           ,[DC_PHI_VT]
           ,[TL_PHI_VT]
           ,[DC_PHI_BH]
           ,[TL_PHI_BH]
           ,[DC_PHI_KHAC]
           ,[TL_PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP4]
		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP5]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[SO_LIEU_SX]
           ,[GIA_SP]
           ,[DC_HOA_HONG]
           ,[DC_BAO_BI]
           ,[DC_DONG_GOI]
           ,[DC_TRO_GIUP]
           ,[DC_BAN_QUYEN]
           ,[DC_TIEN_TRA_SD]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[LOI_NHUAN]
           ,[PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[SO_LIEU_SX]
           ,[GIA_SP]
           ,[DC_HOA_HONG]
           ,[DC_BAO_BI]
           ,[DC_DONG_GOI]
           ,[DC_TRO_GIUP]
           ,[DC_BAN_QUYEN]
           ,[DC_TIEN_TRA_SD]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[LOI_NHUAN]
           ,[PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP5]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGKB_PP6]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[THONG_TIN_SD]
           ,[CHUNG_TU_KEM]
           ,[MA_AP_DUNG_PP]
           ,[GIAI_TRINH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[THONG_TIN_SD]
           ,[CHUNG_TU_KEM]
           ,[MA_AP_DUNG_PP]
           ,[GIAI_TRINH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
	 FROM	
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGKB_PP6]

Set identity_insert [dbo].[GN_ApGia] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_ApGia]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[DON_GIA_NT]
           ,[TRI_GIA_NT]
           ,[DON_GIA_TT]
           ,[TRI_GIA_TT]
           ,[DON_GIA_USD]
           ,[CHAP_NHAN_KB]
           ,[MA_PP_AP]
           ,[MA_GN_THUE]
           ,[MA_CAP_DC]
           ,[MA_LY_DO_DC]
           ,[SO_LUONG_HD]
           ,[TRI_GIA_HD_CHUA_GIAMGIA]
           ,[TRI_GIA_HD_DA_GIAMGIA]
           ,[LOAI_GIAM_GIA]
           ,[NOI_DUNG_KHAC]
           ,[NGAY_AP]
           ,[NGUOI_AP]
           ,[XAC_DINH_GIA]
           ,[THUE_THUC_NOP]
           ,[MOI_NHAT]
           ,[MA_HQQL_RR_TD]
           ,[ID_BANG_RR_TD]
           ,[ID_HANG_RR_TD]
           ,[DON_GIA_NT_KIEM_TRA]
           ,[RR_TD]
           ,[TY_GIA_USD]
           ,[TY_GIA_NT]
           ,[MA_DVT]
           ,[LUONG])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[DON_GIA_NT]
           ,[TRI_GIA_NT]
           ,[DON_GIA_TT]
           ,[TRI_GIA_TT]
           ,[DON_GIA_USD]
           ,[CHAP_NHAN_KB]
           ,[MA_PP_AP]
           ,[MA_GN_THUE]
           ,[MA_CAP_DC]
           ,[MA_LY_DO_DC]
           ,[SO_LUONG_HD]
           ,[TRI_GIA_HD_CHUA_GIAMGIA]
           ,[TRI_GIA_HD_DA_GIAMGIA]
           ,[LOAI_GIAM_GIA]
           ,[NOI_DUNG_KHAC]
           ,[NGAY_AP]
           ,[NGUOI_AP]
           ,[XAC_DINH_GIA]
           ,[THUE_THUC_NOP]
           ,[MOI_NHAT]
           ,[MA_HQQL_RR_TD]
           ,[ID_BANG_RR_TD]
           ,[ID_HANG_RR_TD]
           ,[DON_GIA_NT_KIEM_TRA]
           ,[RR_TD]
           ,[TY_GIA_USD]
           ,[TY_GIA_NT]
           ,[MA_DVT]
           ,[LUONG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_ApGia]
Set identity_insert [dbo].[GN_ApGia] off

Set identity_insert [dbo].[GN_ApGia_XK] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_ApGia_XK]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[DON_GIA_NT]
           ,[TRI_GIA_NT]
           ,[DON_GIA_TT]
           ,[TRI_GIA_TT]
           ,[DON_GIA_USD]
           ,[THUE_SUAT_XNK]
           ,[THUE_SUAT_TTDB]
           ,[THUE_SUAT_VAT]
           ,[THUE_XNK]
           ,[THUE_TTDB]
           ,[THUE_VAT]
           ,[TY_LE_THU_KHAC]
           ,[TRI_GIA_THU_KHAC]
           ,[MA_GN_THUE]
           ,[MA_CAP_DC]
           ,[MA_LY_DO_DC]
           ,[NOI_DUNG_KHAC]
           ,[NGAY_AP]
           ,[NGUOI_AP]
           ,[XAC_DINH_GIA]
           ,[THUE_THUC_NOP]
           ,[MOI_NHAT]
           ,[MA_HQQL_RR_TD]
           ,[ID_BANG_RR_TD]
           ,[ID_HANG_RR_TD]
           ,[DON_GIA_NT_KIEM_TRA]
           ,[RR_TD]
           ,[NGAY_CHOT_GIA]
           ,[TY_GIA_USD]
           ,[TY_GIA_NT]
           ,[MA_DVT]
           ,[LUONG])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[DON_GIA_NT]
           ,[TRI_GIA_NT]
           ,[DON_GIA_TT]
           ,[TRI_GIA_TT]
           ,[DON_GIA_USD]
           ,[THUE_SUAT_XNK]
           ,[THUE_SUAT_TTDB]
           ,[THUE_SUAT_VAT]
           ,[THUE_XNK]
           ,[THUE_TTDB]
           ,[THUE_VAT]
           ,[TY_LE_THU_KHAC]
           ,[TRI_GIA_THU_KHAC]
           ,[MA_GN_THUE]
           ,[MA_CAP_DC]
           ,[MA_LY_DO_DC]
           ,[NOI_DUNG_KHAC]
           ,[NGAY_AP]
           ,[NGUOI_AP]
           ,[XAC_DINH_GIA]
           ,[THUE_THUC_NOP]
           ,[MOI_NHAT]
           ,[MA_HQQL_RR_TD]
           ,[ID_BANG_RR_TD]
           ,[ID_HANG_RR_TD]
           ,[DON_GIA_NT_KIEM_TRA]
           ,[RR_TD]
           ,[NGAY_CHOT_GIA]
           ,[TY_GIA_USD]
           ,[TY_GIA_NT]
           ,[MA_DVT]
           ,[LUONG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_ApGia_XK]
Set identity_insert [dbo].[GN_ApGia_XK] off		

Set identity_insert [dbo].[GN_TKTGAG_PP1] on			
INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP1]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_AP_GIA]
           ,[ID_TKTG]
           ,[NGAY_XK]
           ,[QUYEN_SD]
           ,[KHONG_XD]
           ,[TRA_THEM]
           ,[TIEN_PHAI_TRA]
           ,[CO_QHDB]
           ,[KIEU_QHDB]
           ,[ANH_HUONG_QH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
           ,[GHI_CHEP_HQ])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_AP_GIA]
           ,[ID_TKTG]
           ,[NGAY_XK]
           ,[QUYEN_SD]
           ,[KHONG_XD]
           ,[TRA_THEM]
           ,[TIEN_PHAI_TRA]
           ,[CO_QHDB]
           ,[KIEU_QHDB]
           ,[ANH_HUONG_QH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
           ,[GHI_CHEP_HQ]     
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP1]
Set identity_insert [dbo].[GN_TKTGAG_PP1] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP1CT]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[ID_TKTG]
           ,[GIA_HOA_DON]
           ,[TT_GIAN_TIEP]
           ,[TRA_TRUOC]
           ,[TONG_CONG_1]
           ,[HOA_HONG]
           ,[PHI_BAO_BI]
           ,[PHI_DONG_GOI]
           ,[TRO_GIUP]
           ,[NGUYEN_LIEU]
           ,[VAT_LIEU]
           ,[CONG_CU]
           ,[THIET_KE]
           ,[BAN_QUYEN]
           ,[TIEN_TRA_SD]
           ,[PHI_VC]
           ,[CP_BH]
           ,[PHI_BH]
           ,[PHI_NOI_DIA]
           ,[TONG_CONG_2]
           ,[PHI_PHAT_SINH]
           ,[TIEN_LAI]
           ,[PHI_KHAC]
           ,[GIAM_GIA]
           ,[TONG_CONG_3]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[ID_TKTG]
           ,[GIA_HOA_DON]
           ,[TT_GIAN_TIEP]
           ,[TRA_TRUOC]
           ,[TONG_CONG_1]
           ,[HOA_HONG]
           ,[PHI_BAO_BI]
           ,[PHI_DONG_GOI]
           ,[TRO_GIUP]
           ,[NGUYEN_LIEU]
           ,[VAT_LIEU]
           ,[CONG_CU]
           ,[THIET_KE]
           ,[BAN_QUYEN]
           ,[TIEN_TRA_SD]
           ,[PHI_VC]
           ,[CP_BH]
           ,[PHI_BH]
           ,[PHI_NOI_DIA]
           ,[TONG_CONG_2]
           ,[PHI_PHAT_SINH]
           ,[TIEN_LAI]
           ,[PHI_KHAC]
           ,[GIAM_GIA]
           ,[TONG_CONG_3]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]     
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP1CT]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP23]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[NGAY_XK]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_TT]
           ,[MA_HQ_TT]
           ,[MA_LH_TT]
           ,[NGAY_DK_TT]
           ,[SO_TK_TT]
           ,[STT_HANG_TT]
           ,[NGAY_XK_TT]
           ,[TRI_GIA_NT_TT]
           ,[DC_CD_TM]
           ,[DC_SL]
           ,[DC_GIAM_GIA]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[TKTG_PP2]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT 
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[NGAY_XK]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_TT]
           ,[MA_HQ_TT]
           ,[MA_LH_TT]
           ,[NGAY_DK_TT]
           ,[SO_TK_TT]
           ,[STT_HANG_TT]
           ,[NGAY_XK_TT]
           ,[TRI_GIA_NT_TT]
           ,[DC_CD_TM]
           ,[DC_SL]
           ,[DC_GIAM_GIA]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[TKTG_PP2]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]     
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP23]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP4]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_KT]
           ,[GIA_BAN_VN]
           ,[TL_GIA_BAN_VN]
           ,[DC_HOA_HONG]
           ,[TL_HOA_HONG]
           ,[DC_LOI_NHUAN]
           ,[TL_LOI_NHUAN]
           ,[DC_PHI_VT]
           ,[TL_PHI_VT]
           ,[DC_PHI_BH]
           ,[TL_PHI_BH]
           ,[DC_PHI_KHAC]
           ,[TL_PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[LYDO_KAD_PPT]
           ,[TEN_HANG_KT]
           ,[GIA_BAN_VN]
           ,[TL_GIA_BAN_VN]
           ,[DC_HOA_HONG]
           ,[TL_HOA_HONG]
           ,[DC_LOI_NHUAN]
           ,[TL_LOI_NHUAN]
           ,[DC_PHI_VT]
           ,[TL_PHI_VT]
           ,[DC_PHI_BH]
           ,[TL_PHI_BH]
           ,[DC_PHI_KHAC]
           ,[TL_PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]     
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP4]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP5]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[SO_LIEU_SX]
           ,[GIA_SP]
           ,[DC_HOA_HONG]
           ,[DC_BAO_BI]
           ,[DC_DONG_GOI]
           ,[DC_TRO_GIUP]
           ,[DC_BAN_QUYEN]
           ,[DC_TIEN_TRA_SD]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[LOI_NHUAN]
           ,[PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT 
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[SO_LIEU_SX]
           ,[GIA_SP]
           ,[DC_HOA_HONG]
           ,[DC_BAO_BI]
           ,[DC_DONG_GOI]
           ,[DC_TRO_GIUP]
           ,[DC_BAN_QUYEN]
           ,[DC_TIEN_TRA_SD]
           ,[DC_PHI_VT]
           ,[DC_PHI_BH]
           ,[LOI_NHUAN]
           ,[PHI_KHAC]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[GIAI_TRINH]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP5]

INSERT INTO [GTT01NghiepVu].[dbo].[GN_TKTGAG_PP6]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[THONG_TIN_SD]
           ,[CHUNG_TU_KEM]
           ,[MA_AP_DUNG_PP]
           ,[GIAI_TRINH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_AP_GIA]
           ,[THONG_TIN_SD]
           ,[CHUNG_TU_KEM]
           ,[MA_AP_DUNG_PP]
           ,[GIAI_TRINH]
           ,[TRI_GIA_NT]
           ,[TRI_GIA_VND]
           ,[NGUOI_KB]
           ,[CHUC_VU_NGUOI_KB]
           ,[NGAY_KB]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TKTGAG_PP6]

Set identity_insert [dbo].[GN_KiemTraGia] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_KiemTraGia]
           ([MA_HQQL]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_KIEM_TRA]
           ,[CAP_KIEM_TRA]
           ,[NGAY_KIEM_TRA]
           ,[NGUOI_KIEM_TRA]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC])
     SELECT
		[MA_HQQL]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[ID_KIEM_TRA]
           ,[CAP_KIEM_TRA]
           ,[NGAY_KIEM_TRA]
           ,[NGUOI_KIEM_TRA]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KiemTraGia]
Set identity_insert [dbo].[GN_KiemTraGia] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_PhucTapGia]
           ([MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[NGAY_PHUC_TAP]
           ,[NGUOI_PHUC_TAP]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC])
     SELECT
		[MA_HQQL]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[NGAY_PHUC_TAP]
           ,[NGUOI_PHUC_TAP]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_PhucTapGia]


INSERT INTO [GTT01NghiepVu].[dbo].[GN_ThamVanGia]
           ([MA_HQQL]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]           
           ,[SO_BIEN_BAN]
           ,[NGAY_THAM_VAN]
           ,[NGUOI_THAM_VAN]
           ,[CAP_THAM_VAN]
           ,[MA_HINH_THUC]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC])
     SELECT
		[MA_HQQL]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[SO_BIEN_BAN]
           ,[NGAY_THAM_VAN]
           ,[NGUOI_THAM_VAN]
           ,[CAP_THAM_VAN]
           ,[MA_HINH_THUC]
           ,[MA_KET_QUA]
           ,[NOI_DUNG_KHAC]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_ThamVanGia]

Set identity_insert [dbo].[GN_ThanhTraGia] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_ThanhTraGia]
           ([MA_HQQL]
           ,[ID_THANH_TRA]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[CQ_THANH_TRA]
           ,[NOI_DUNG_KHAC])
     SELECT
		[MA_HQQL]
		,[ID_THANH_TRA]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[CQ_THANH_TRA]
           ,[NOI_DUNG_KHAC]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_ThanhTraGia]
Set identity_insert [dbo].[GN_ThanhTraGia] off
		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_ThanhTraGia_Hang]
           ([MA_HQQL_TT]
           ,[ID_THANH_TRA]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_KET_QUA])
     SELECT
		[MA_HQQL_TT]
           ,[ID_THANH_TRA]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_KET_QUA]
	 FROM	
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_ThanhTraGia_Hang]

Set identity_insert [dbo].[GN_KiemTraSTQ] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_KiemTraSTQ]
           ([MA_HQQL]
           ,[ID_KIEM_TRA_STQ]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[CQ_KIEM_TRA_STQ]
           ,[NOI_DUNG_KHAC])
     SELECT
		[MA_HQQL]
		,[ID_KIEM_TRA_STQ]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[CQ_KIEM_TRA_STQ]
           ,[NOI_DUNG_KHAC]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KiemTraSTQ]
Set identity_insert [dbo].[GN_KiemTraSTQ] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_KiemTraSTQ_Hang]
           ([MA_HQQL_STQ]
           ,[ID_KIEM_TRA_STQ]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_KET_QUA])
     SELECT
		[MA_HQQL_STQ]
           ,[ID_KIEM_TRA_STQ]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_KET_QUA]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KiemTraSTQ_Hang]

Set identity_insert [dbo].[GN_TTNguonKhac] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_TTNguonKhac]
           ([MA_HQQL]
           ,[ID_NGUONKHAC]
           ,[MA_HANG]
           ,[TEN_HANG]
           ,[TEN_TM]
           ,[MA_NUOC_XX]
           ,[LUONG]
           ,[MA_PTVT]
           ,[MA_NGUON_TT]
           ,[CAP_DO_TM]
           ,[NGAY_BAN]
           ,[GIA_BAN]
           ,[MA_NT_GIA_BAN]
           ,[THUE_SUAT_XNK]
           ,[THUE_SUAT_VAT]
           ,[THUE_SUAT_TTDB]
           ,[THUE_KHAC]
           ,[TY_LE_CHI_PHI_LOI_NHUAN]
           ,[TY_GIA_NT]
           ,[TY_GIA_USD]
           ,[MA_DVT]
           ,[MA_DVT_QUYDOI]
           ,[GIA_TRI_QUY_DOI]
           ,[GIA_NK_QUY_DOI_USD]
           ,[GIA_NK_QUY_DOI_DVT]
           ,[NGAY_NHAP]
           ,[NGUOI_NHAP]
           ,[CAN_BO_DE_XUAT]
           ,[NGAY_PHE_DUYET]
           ,[LANH_DAO_PHE_DUYET]
           ,[SO_CONG_VAN])
     SELECT
		[MA_HQQL]
		,[ID_NGUONKHAC]
           ,[MA_HANG]
           ,[TEN_HANG]
           ,[TEN_TM]
           ,[MA_NUOC_XX]
           ,[LUONG]
           ,[MA_PTVT]
           ,[MA_NGUON_TT]
           ,[CAP_DO_TM]
           ,[NGAY_BAN]
           ,[GIA_BAN]
           ,[MA_NT_GIA_BAN]
           ,[THUE_SUAT_XNK]
           ,[THUE_SUAT_VAT]
           ,[THUE_SUAT_TTDB]
           ,[THUE_KHAC]
           ,[TY_LE_CHI_PHI_LOI_NHUAN]
           ,[TY_GIA_NT]
           ,[TY_GIA_USD]
           ,[MA_DVT]
           ,[MA_DVT_QUYDOI]
           ,[GIA_TRI_QUY_DOI]
           ,[GIA_NK_QUY_DOI_USD]
           ,[GIA_NK_QUY_DOI_DVT]
           ,[NGAY_NHAP]
           ,[NGUOI_NHAP]
           ,[CAN_BO_DE_XUAT]
           ,[NGAY_PHE_DUYET]
           ,[LANH_DAO_PHE_DUYET]
           ,[SO_CONG_VAN]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TTNguonKhac]
Set identity_insert [dbo].[GN_TTNguonKhac] off

Set identity_insert [dbo].[GN_TTNguonKhac_Picture] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_TTNguonKhac_Picture]
           ([MA_HQQL]
           ,[ID_NGUONKHAC]
           ,[ID_NGUONKHAC_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile])
     SELECT
		[MA_HQQL]
           ,[ID_NGUONKHAC]
           ,[ID_NGUONKHAC_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_TTNguonKhac_Picture]
Set identity_insert [dbo].[GN_TTNguonKhac_Picture] off

Set identity_insert [dbo].[GN_KhieuNai] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_KhieuNai]
           ([MA_HQQL]
           ,[ID_KHIEU_NAI]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[MA_DV]
           ,[SO_TK]
           ,[MA_LH]
           ,[MA_HQ]
           ,[NGAY_DK]
           ,[MA_LDKN]
           ,[MAT_HANG_KN]
           ,[NOI_DUNG_KN]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[NOI_DUNG_QD]
           ,[NGUOI_XL]
           ,[CAP_XL]
           ,[KQ_XL])
     SELECT
		[MA_HQQL]
		,[ID_KHIEU_NAI]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[MA_DV]
           ,[SO_TK]
           ,[MA_LH]
           ,[MA_HQ]
           ,[NGAY_DK]
           ,[MA_LDKN]
           ,[MAT_HANG_KN]
           ,[NOI_DUNG_KN]
           ,[SO_QD]
           ,[NGAY_QD]
           ,[NOI_DUNG_QD]
           ,[NGUOI_XL]
           ,[CAP_XL]
           ,[KQ_XL]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KhieuNai]
Set identity_insert [dbo].[GN_KhieuNai] off
	
INSERT INTO [GTT01NghiepVu].[dbo].[GN_KhieuNai_Hang]
           ([MA_HQQL_KN]
           ,[ID_KHIEU_NAI]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG])
     SELECT
		[MA_HQQL_KN]
           ,[ID_KHIEU_NAI]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KhieuNai_Hang]

Set identity_insert [dbo].[GN_KHIEUNAI_PICTURE] on	
INSERT INTO [GTT01NghiepVu].[dbo].[GN_KHIEUNAI_PICTURE]
           ([MA_HQQL]
           ,[ID_KHIEU_NAI]
           ,[ID_KHIEU_NAI_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile])
     SELECT
		[MA_HQQL]
           ,[ID_KHIEU_NAI]
           ,[ID_KHIEU_NAI_PICTURE]
           ,[TenFile]
           ,[MoTaFile]
           ,[PictureFile]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_KHIEUNAI_PICTURE]
Set identity_insert [dbo].[GN_KHIEUNAI_PICTURE] off

Set identity_insert [dbo].[GN_BangRRDeXuatChiCuc] on			
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatChiCuc]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT])
     SELECT
		[MA_HQQL]
		,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatChiCuc]
Set identity_insert [dbo].[GN_BangRRDeXuatChiCuc] off

Set identity_insert [dbo].[GN_BangRRDeXuatChiCucCT] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatChiCucCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]           
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]           
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatChiCucCT]
Set identity_insert [dbo].[GN_BangRRDeXuatChiCucCT] off

Set identity_insert [dbo].[GN_BangRRDeXuatCuc] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatCuc]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT])
     SELECT
		[MA_HQQL]
		,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatCuc]
Set identity_insert [dbo].[GN_BangRRDeXuatCuc] off

Set identity_insert [dbo].[GN_BangRRDeXuatCucCT] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatCucCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatCucCT]
Set identity_insert [dbo].[GN_BangRRDeXuatCucCT] off

Set identity_insert [dbo].[GN_BangRRDeXuatTongCuc] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatTongCuc]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT])
     SELECT
		[MA_HQQL]
		,[ID_BANG_RR_DX]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[LANH_DAO_PHE_DUYET]
           ,[MOI_NHAT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatTongCuc]
Set identity_insert [dbo].[GN_BangRRDeXuatTongCuc] off

Set identity_insert [dbo].[GN_BangRRDeXuatTongCucCT] on			
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRDeXuatTongCucCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_DX]
           ,[ID_HANG_RR_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRDeXuatTongCucCT]
Set identity_insert [dbo].[GN_BangRRDeXuatTongCucCT] off

Set identity_insert [dbo].[GN_BangRRCoSo] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRCoSo]
           ([MA_HQQL]
           ,[ID_BANG_RR_CS]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT])
     SELECT
		[MA_HQQL]
		,[ID_BANG_RR_CS]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRCoSo]
Set identity_insert [dbo].[GN_BangRRCoSo] off

Set identity_insert [dbo].[GN_BangRRCoSoCT] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRCoSoCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_CS]
           ,[ID_HANG_RR_CS]
           ,[MA_HQQL_DX]
           ,[ID_BANG_DX]
           ,[ID_HANG_DX]
           ,[GIA_DE_XUAT_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_CS]
           ,[ID_HANG_RR_CS]
           ,[MA_HQQL_DX]
           ,[ID_BANG_DX]
           ,[ID_HANG_DX]
           ,[GIA_DE_XUAT_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRCoSoCT]
Set identity_insert [dbo].[GN_BangRRCoSoCT] off

Set identity_insert [dbo].[GN_BangRRSuDung] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRSuDung]
           ([MA_HQQL]
           ,[ID_BANG_RR_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[NGAY_HIEU_LUC]
           ,[MOI_NHAT]
           ,[HET_HIEU_LUC]
           ,[NGAY_HET_HIEU_LUC]
           ,[ID_BANG_QD_HET_HL])
     SELECT
		[MA_HQQL]
		,[ID_BANG_RR_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[NGAY_HIEU_LUC]
           ,[MOI_NHAT]
           ,[HET_HIEU_LUC]
           ,[NGAY_HET_HIEU_LUC]
           ,[ID_BANG_QD_HET_HL]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRSuDung]
Set identity_insert [dbo].[GN_BangRRSuDung] off

Set identity_insert [dbo].[GN_BangRRSuDungCT] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRSuDungCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_SD]
           ,[ID_HANG_RR_SD]
           ,[MA_HQQL_CS]
           ,[ID_BANG_CS]
           ,[ID_HANG_CS]
           ,[ID_THEO_DOI]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_KIEM_TRA]
           ,[GHI_CHU]
           ,[STT]
           ,[STT_ORDER]
           ,[HIEN_THI])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_SD]
           ,[ID_HANG_RR_SD]
           ,[MA_HQQL_CS]
           ,[ID_BANG_CS]
           ,[ID_HANG_CS]
           ,[ID_THEO_DOI]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_KIEM_TRA]
           ,[GHI_CHU]
           ,[STT]
           ,[STT_ORDER]
           ,[HIEN_THI]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRSuDungCT]
Set identity_insert [dbo].[GN_BangRRSuDungCT] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangRRSuDungXoaCT]
           ([MA_HQQL]
           ,[ID_BANG_RR_SD]
           ,[ID_BANG_RR_SD_XOA]
           ,[ID_HANG_RR_SD_XOA])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_RR_SD]
           ,[ID_BANG_RR_SD_XOA]
           ,[ID_HANG_RR_SD_XOA]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangRRSuDungXoaCT]

Set identity_insert [dbo].[GN_BangDMRRSuDung] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangDMRRSuDung]
           ([MA_HQQL]
           ,[ID_BANG_DM_RR_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT])
     SELECT
		[MA_HQQL]
		,[ID_BANG_DM_RR_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangDMRRSuDung]
Set identity_insert [dbo].[GN_BangDMRRSuDung] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangDMRRSuDungCT]
           ([MA_HQQL]
           ,[ID_BANG_DM_RR_SD]           
           ,[ID_BANG_RR_SD]
           ,[ID_HANG_RR_SD])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_DM_RR_SD]
           ,[ID_BANG_RR_SD]
           ,[ID_HANG_RR_SD]
	 FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangDMRRSuDungCT]

Set identity_insert [dbo].[GN_BangTDDeXuat] on	
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDDeXuat]
       ([MA_HQQL]
       ,[ID_BANG_TD_DX]
       ,[NGUOI_LAP]
       ,[NGAY_LAP]
       ,[SO_CV]
       ,[NGAY_CV]
       ,[LANH_DAO_PHE_DUYET]
       ,[MOI_NHAT]
       ,[LOAI_HANG])
	 SELECT
		 [MA_HQQL]
		 ,[ID_BANG_TD_DX]
		   ,[NGUOI_LAP]
		   ,[NGAY_LAP]
		   ,[SO_CV]
		   ,[NGAY_CV]
		   ,[LANH_DAO_PHE_DUYET]
		   ,[MOI_NHAT]
		   ,[LOAI_HANG]
	 FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDDeXuat]	
Set identity_insert [dbo].[GN_BangTDDeXuat] off

Set identity_insert [dbo].[GN_BangTDDeXuatCT] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDDeXuatCT]
           ([MA_HQQL]
           ,[ID_BANG_TD_DX]
           ,[ID_HANG_TD_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_TD_DX]
           ,[ID_HANG_TD_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDDeXuatCT]
Set identity_insert [dbo].[GN_BangTDDeXuatCT] off

Set identity_insert [dbo].[GN_BangTDCoSo] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDCoSo]
           ([MA_HQQL]
           ,[ID_BANG_TD_CS]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
           ,[LOAI_HANG])
     SELECT
		[MA_HQQL]
		,[ID_BANG_TD_CS]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
           ,[LOAI_HANG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDCoSo]
Set identity_insert [dbo].[GN_BangTDCoSo] off

Set identity_insert [dbo].[GN_BangTDCoSoCT] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDCoSoCT]
           ([MA_HQQL]
           ,[ID_BANG_TD_CS]
           ,[ID_HANG_TD_CS]
           ,[MA_HQQL_DX]
           ,[ID_BANG_DX]
           ,[ID_HANG_DX]
           ,[GIA_DE_XUAT_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_TD_CS]
           ,[ID_HANG_TD_CS]
           ,[MA_HQQL_DX]
           ,[ID_BANG_DX]
           ,[ID_HANG_DX]
           ,[GIA_DE_XUAT_DX]
           ,[MA_HQQL_SD]
           ,[ID_BANG_SD]
           ,[ID_HANG_SD]
           ,[ID_THEO_DOI]
           ,[MA_HQQL_NGUONKHAC]
           ,[ID_NGUONKHAC]
           ,[TEN_NGUONKHAC]
           ,[DON_GIA_NGUYEN_TE_NGUONKHAC]
           ,[DON_GIA_USD_NGUONKHAC]
           ,[DON_GIA_QUY_DOI_NGUONKHAC]
           ,[MA_HQQL_TK]
           ,[ID_TO_KHAI]
           ,[ID_HANG]
           ,[MA_HQQL_TK_KHAI_BAO_MIN]
           ,[ID_TO_KHAI_KHAI_BAO_MIN]
           ,[ID_HANG_KHAI_BAO_MIN]
           ,[MA_HQQL_TK_KHAI_BAO_MAX]
           ,[ID_TO_KHAI_KHAI_BAO_MAX]
           ,[ID_HANG_KHAI_BAO_MAX]
           ,[MA_HQQL_TK_DIEU_CHINH_MIN]
           ,[ID_TO_KHAI_DIEU_CHINH_MIN]
           ,[ID_HANG_DIEU_CHINH_MIN]
           ,[MA_HQQL_TK_DIEU_CHINH_MAX]
           ,[ID_TO_KHAI_DIEU_CHINH_MAX]
           ,[ID_HANG_DIEU_CHINH_MAX]
           ,[GIA_KHAI_BAO_MIN]
           ,[GIA_KHAI_BAO_MAX]
           ,[GIA_DIEU_CHINH_MIN]
           ,[GIA_DIEU_CHINH_MAX]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_DE_XUAT]
           ,[GHI_CHU]
           ,[STT]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDCoSoCT]
Set identity_insert [dbo].[GN_BangTDCoSoCT] off

Set identity_insert [dbo].[GN_BangTDSuDung] on		
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDSuDung]
           ([MA_HQQL]
           ,[ID_BANG_TD_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[NGAY_HIEU_LUC]
           ,[MOI_NHAT]
           ,[HET_HIEU_LUC]
           ,[NGAY_HET_HIEU_LUC]
           ,[ID_BANG_QD_HET_HL]
           ,[LOAI_HANG])
     SELECT
		[MA_HQQL]
		,[ID_BANG_TD_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[SO_CV]
           ,[NGAY_CV]
           ,[NGAY_HIEU_LUC]
           ,[MOI_NHAT]
           ,[HET_HIEU_LUC]
           ,[NGAY_HET_HIEU_LUC]
           ,[ID_BANG_QD_HET_HL]
           ,[LOAI_HANG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDSuDung]
Set identity_insert [dbo].[GN_BangTDSuDung] off
Set identity_insert [dbo].[GN_BangTDSuDungCT] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDSuDungCT]
           ([MA_HQQL]
           ,[ID_BANG_TD_SD]
           ,[ID_HANG_TD_SD]
           ,[MA_HQQL_CS]
           ,[ID_BANG_CS]
           ,[ID_HANG_CS]
           ,[ID_THEO_DOI]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_KIEM_TRA]
           ,[GHI_CHU]
           ,[STT]
           ,[STT_ORDER]
           ,[HIEN_THI])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_TD_SD]
           ,[ID_HANG_TD_SD]
           ,[MA_HQQL_CS]
           ,[ID_BANG_CS]
           ,[ID_HANG_CS]
           ,[ID_THEO_DOI]
           ,[MA_HS]
           ,[TEN_HANG]
           ,[NHAN_HIEU]
           ,[MODEL]
           ,[NAM_SX]
           ,[MA_NUOC_XX]
           ,[MA_DVT]
           ,[TEN_NUOC_XX]
           ,[TEN_DVT]
           ,[GIA_KIEM_TRA]
           ,[GHI_CHU]
           ,[STT]
           ,[STT_ORDER]
           ,[HIEN_THI]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDSuDungCT]
Set identity_insert [dbo].[GN_BangTDSuDungCT] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangTDSuDungXoaCT]
           ([MA_HQQL]
           ,[ID_BANG_TD_SD]
           ,[ID_BANG_TD_SD_XOA]
           ,[ID_HANG_TD_SD_XOA])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_TD_SD]
           ,[ID_BANG_TD_SD_XOA]
           ,[ID_HANG_TD_SD_XOA]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangTDSuDungXoaCT]

Set identity_insert [dbo].[GN_BangDMTDSuDung] on
INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangDMTDSuDung]
           ([MA_HQQL]
           ,[ID_BANG_DM_TD_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
           ,[LOAI_HANG])
     SELECT
		[MA_HQQL]
		,[ID_BANG_DM_TD_SD]
           ,[NGUOI_LAP]
           ,[NGAY_LAP]
           ,[MO_TA]
           ,[MOI_NHAT]
           ,[LOAI_HANG]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangDMTDSuDung]
Set identity_insert [dbo].[GN_BangDMTDSuDung] off

INSERT INTO [GTT01NghiepVu].[dbo].[GN_BangDMTDSuDungCT]
           ([MA_HQQL]
           ,[ID_BANG_DM_TD_SD]
           ,[ID_BANG_TD_SD]
           ,[ID_HANG_TD_SD])
     SELECT
		[MA_HQQL]
           ,[ID_BANG_DM_TD_SD]
           ,[ID_BANG_TD_SD]
           ,[ID_HANG_TD_SD]
     FROM
		[GTT_TT].[GTT01NghiepVu].[dbo].[GN_BangDMTDSuDungCT]    	
