USE SXXK
GO

-----Theo don vi	
DECLARE @MA_DV VARCHAR(50)
SET @MA_DV='0500556081'

SELECT 
	A.MA_NPL, SUM(A.TON) AS TON
FROM
	(
		SELECT SOTK,MA_LH,MA_HQ,NAMDK,MA_NPL,TON FROM DNPLNHAP WHERE MA_DV=@MA_DV AND TON > 0
		UNION 
		SELECT 
			A.SOTK,A.MA_LH,A.MA_HQ,A.NAMDK,A.MA_NPL_SP MA_NPL,A.LUONG AS TON
		FROM
			DHANGMDDK A INNER JOIN DTOKHAIMD B
			ON A.SOTK=B.SOTK AND A.MA_HQ=B.MA_HQ AND A.MA_LH=B.MA_LH AND A.NAMDK=B.NAMDK 
		WHERE 
			LEFT(B.MA_LH,1) ='N'
			AND B.THANH_LY = ''
			AND B.MA_DV=@MA_DV	
	) A
GROUP BY
	A.MA_NPL
	
